feat(Vlog.cs): Create model for Vlog entity
Simplon-hdf/Projet-DotNet-P6-LJMA pull request #7
Opened 2024-08-05 14:14 UTC by wazeeeeee

2024-08-05 14:20 UTC, AngelPASTORROJAS requested changes
Attention à la mise en forme de ton code

2024-08-05 14:20 UTC, AngelPASTORROJAS commented on Projet-DotNet-P6-LJMA/Models/Vlog.cs
Attention à la mise en forme de ton code

2024-08-05 14:26 UTC, wazeeeeee commented
> Attention à la mise en forme de ton code

J'ai corrigé la mise en forme du code

2024-08-05 14:26 UTC, AngelPASTORROJAS approved these changes, later dismissed

2024-08-06 07:20 UTC, Srekaens approved these changes, later dismissed

2024-08-06 08:02 UTC, AngelPASTORROJAS approved these changes

2024-08-06 08:06 UTC, AngelPASTORROJAS approved these changes

2024-08-06 08:07 UTC, Srekaens approved these changes

2024-08-06 08:07 UTC, MrLkuch approved these changes

2024-08-06 08:08 UTC, merged